CREATE TABLE `leads` (
	`id` text PRIMARY KEY NOT NULL,
	`project` text NOT NULL,
	`repo` text NOT NULL,
	`source` text NOT NULL,
	`source_url` text NOT NULL,
	`discovered_at` text NOT NULL,
	`stack` text NOT NULL,
	`category` text NOT NULL,
	`reward` text NOT NULL,
	`funding_signal` text NOT NULL,
	`deadline` text NOT NULL,
	`launch_stage` text NOT NULL,
	`existing_audits` text NOT NULL,
	`bounty_program` text NOT NULL,
	`contact` text NOT NULL,
	`fit_reason` text NOT NULL,
	`suggested_scope` text NOT NULL,
	`outreach_draft` text NOT NULL,
	`stage` text DEFAULT 'New' NOT NULL,
	`score` integer NOT NULL,
	`score_breakdown` text NOT NULL,
	`summary` text NOT NULL,
	`synced_at` text NOT NULL
);
