import type { leads } from "../db/schema";

type LeadRow=typeof leads.$inferInsert;
type JobPosting={"@type"?:string;title?:string;description?:string;datePosted?:string;validThrough?:string;url?:string;employmentType?:string|string[];hiringOrganization?:{name?:string};baseSalary?:unknown};

const now=()=>new Date().toISOString();
const clean=(value:string)=>value.replaceAll("&amp;","&").replaceAll("&gt;",">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const dateLabel=(value:string|null|undefined)=>{if(!value)return "See official source";const date=new Date(value);return Number.isNaN(date.getTime())?"See official source":date.toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"})};
const money=(value:number,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(value);
const scoreParts=(quality:number,earning:number)=>({qualityBreakdown:JSON.stringify({Legitimacy:25,"Budget signal":quality>=80?18:12,Freshness:15,Urgency:12,"Opportunity clarity":12,Contactability:10}),earningBreakdown:JSON.stringify({"Reward strength":earning>=70?20:12,"Competition advantage":18,"Reward options":18,Timing:15,Difficulty:8,Evidence:5})});

function row(input:{id:string;project:string;source:string;sourceUrl:string;stack:string;category:"Hackathon"|"Job"|"Internship";reward:string;deadline:string;summary:string;evidenceNote:string;rewardPaths:string[];difficulty:string;competitionLevel:string;visibilityLevel:string;quality:number;earning:number;technologies?:string[];topics?:string[];ecosystem?:string;launchStage:string}):LeadRow{
  const scores=scoreParts(input.quality,input.earning);
  return {id:input.id,project:input.project,repo:input.category==="Hackathon"?"Build submission":"Official application page",source:input.source,sourceUrl:input.sourceUrl,discoveredAt:"Current listing",stack:input.stack,category:input.category,reward:input.reward,fundingSignal:input.reward.includes("not published")?"Compensation not published":"Published or event-level reward signal",deadline:input.deadline,launchStage:input.launchStage,existingAudits:"Not applicable",bountyProgram:input.category==="Hackathon"?"Official builder competition":"Employment opportunity",contact:`Use the official ${input.source} application route`,fitReason:input.category==="Hackathon"?"Multiple prize tracks can create a stronger reward-to-competition edge when matched to reusable skills.":`A fresh ${input.category.toLowerCase()} listing ranked by stack match, experience fit, and recency.`,suggestedScope:input.category==="Hackathon"?"Compare sponsor tracks, participant visibility, delivery time, and reusable code before committing. Prefer the narrowest credible track where your existing work creates an edge.":"Confirm the role is open, review location and eligibility, then tailor your application to the official description.",outreachDraft:input.category==="Hackathon"?"Apply through the official event page and map your strongest existing work to the least-crowded credible prize track.":`I am interested in ${input.project}. My background aligns with the published stack, and I would be glad to share relevant work.`,stage:"New",score:input.quality,scoreBreakdown:scores.qualityBreakdown,summary:input.summary,evidenceConfidence:"observed",evidenceNote:input.evidenceNote,topics:JSON.stringify(input.topics||[input.category]),technologies:JSON.stringify(input.technologies||input.stack.split(/\s*\/\s*/)),ecosystem:input.ecosystem||"Multi-chain",sourceTier:"Owner feed",rewardPaths:JSON.stringify(input.rewardPaths),difficulty:input.difficulty,competitionLevel:input.competitionLevel,competitionConfidence:"estimated",visibilityLevel:input.visibilityLevel,winnerCount:input.category==="Hackathon"?3:1,participationRewards:false,earningScore:input.earning,earningBreakdown:scores.earningBreakdown,syncedAt:now()};
}

async function page(url:string){const response=await fetch(url,{headers:{"User-Agent":"Proskopos/1.0 owner opportunity feed",Accept:"text/html"},signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error(`${response.status} from ${url}`);return response.text()}
function careerStack(text:string){const rules:Array<[RegExp,string]>= [[/solidity|ethereum|evm/i,"Solidity / EVM"],[/rust|solana/i,"Rust / Solana"],[/\bmove\b|sui|aptos/i,"Move"],[/cairo|starknet/i,"Cairo"],[/soroban|stellar/i,"Soroban"],[/react|typescript|javascript|node/i,"Web / API"]];return rules.find(([pattern])=>pattern.test(text))?.[1]||"Web3"}
function salaryLabel(value:unknown){if(!value||typeof value!=="object")return "Salary not published";const salary=value as {currency?:string;value?:number|{minValue?:number;maxValue?:number;value?:number;unitText?:string}};const amount=typeof salary.value==="number"?salary.value:salary.value?.value||salary.value?.maxValue||salary.value?.minValue;return amount?`${money(amount,salary.currency||"USD")}${typeof salary.value==="object"&&salary.value.unitText?` / ${salary.value.unitText.toLowerCase()}`:""}`:"Salary not published"}

async function collectCareerPage(url:string,forceInternship=false):Promise<LeadRow[]>{
  const html=await page(url);const rows:LeadRow[]=[];
  for(const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){
    let posting:JobPosting;try{posting=JSON.parse(match[1]) as JobPosting}catch{continue}
    if(posting["@type"]!=="JobPosting"||!posting.title)continue;
    const description=clean(posting.description||"").slice(0,600);const company=clean(posting.hiringOrganization?.name||"Web3 company");const category=forceInternship||/intern|graduate|trainee|apprentice/i.test(`${posting.title} ${posting.employmentType||""}`)?"Internship":"Job";const stack=careerStack(`${posting.title} ${description}`);const salary=salaryLabel(posting.baseSalary);const slug=`${company}-${posting.title}-${posting.datePosted||""}`.toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,100);
    rows.push(row({id:`web3career-${slug}`,project:`${posting.title} ? ${company}`,source:"Web3 Career",sourceUrl:posting.url||url,stack,category,reward:salary,deadline:dateLabel(posting.validThrough),summary:description||`${company} has a recently listed ${posting.title} opening.`,evidenceNote:"Title, employer, posting date, deadline, compensation when available, and application URL were observed in structured JobPosting data.",rewardPaths:[category==="Internship"?"Paid experience":"Employment compensation"],difficulty:category==="Internship"?"Beginner":"Intermediate",competitionLevel:"Moderate",visibilityLevel:"High",quality:salary==="Salary not published"?74:84,earning:salary==="Salary not published"?60:74,topics:[category==="Internship"?"Early Career":"Web3 Careers"],launchStage:"Recently posted"}));
  }
  return rows.slice(0,forceInternship?8:12);
}

export async function collectWeb3Jobs():Promise<LeadRow[]>{const [jobs,internships]=await Promise.all([collectCareerPage("https://web3.career/remote-jobs"),collectCareerPage("https://web3.career/intern%2Bremote-jobs",true)]);return Array.from(new Map([...internships,...jobs].map((item)=>[item.id,item])).values()).slice(0,16)}

export async function collectEthGlobal():Promise<LeadRow[]>{
  const html=await page("https://ethglobal.com/events");const rows:LeadRow[]=[];
  for(const match of html.matchAll(/href="\/events\/([^"]+)"[^>]*>([\s\S]{0,12000}?)<\/a>/g)){
    const [,slug,body]=match;const title=clean(body.match(/<h2[^>]*>([\s\S]*?)<\/h2>/)?.[1]||"");const eventType=clean(body.match(/<span class="[^"]*">([^<]*(?:Hackathon|Online)[^<]*)<\/span>/i)?.[1]||"");
    if(!title||!/hackathon|online/i.test(eventType)||rows.some((item)=>item.id===`ethglobal-${slug}`))continue;
    const month=clean(body.match(/uppercase[^>]*>([^<]+)</)?.[1]||"");const days=[...body.matchAll(/<span class="">(\d{1,2})<\/span>/g)].map((item)=>item[1]).slice(0,2);const deadline=[month,...days].filter(Boolean).join("?")||"See event page";
    rows.push(row({id:`ethglobal-${slug}`,project:title,source:"ETHGlobal",sourceUrl:`https://ethglobal.com/events/${slug}`,stack:"Solidity / EVM",category:"Hackathon",reward:"Prize tracks published per event",deadline,summary:`${title} is listed by ETHGlobal as ${eventType}. Multiple sponsor tracks create more than one path to earning.`,evidenceNote:"Event name, format, and application route were extracted from ETHGlobal's official upcoming events page. Prize and participant estimates should be confirmed on the event page.",rewardPaths:["Sponsor tracks","Finalist recognition","Multiple winners"],difficulty:"Intermediate",competitionLevel:"High",visibilityLevel:"High",quality:82,earning:67,technologies:["Solidity","EVM"],topics:["Web3 Hackathon","Builder Competition"],ecosystem:"Ethereum",launchStage:/online/i.test(eventType)?"Upcoming online hackathon":"Upcoming IRL hackathon"}));
  }
  return rows.slice(0,8);
}
