"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
declare global{interface Window{google?:{accounts:{id:{initialize:(options:{client_id:string;callback:(response:{credential:string})=>void})=>void;renderButton:(element:HTMLElement,options:Record<string,string>)=>void}}}}}

type Profile = { displayName:string; goals:string[]; stacks:string[]; chains:string[]; specialties:string[]; experienceLevel:string; portfolioUrl:string; minReward:number; availability:string; region:string; scopedOnly:boolean; alertFrequency:string; alertChannel:string; alertDestination:string; passportHeadline:string; passportBio:string; passportSlug:string; passportPublic:boolean; githubUrl:string; auditReportUrls:string[]; onboardingComplete:boolean };
type LeadState = { saved:boolean; hidden:boolean; pitchedAt:string|null; notes:string; nextActionAt:string|null; outcome:string; outcomeNote:string };
type Lead = { id:string; project:string; repo:string; source:string; sourceUrl:string; discoveredAt:string; stack:string; category:string; reward:string; fundingSignal:string; deadline:string; launchStage:string; existingAudits:string; bountyProgram:string; contact:string; fitReason:string; suggestedScope:string; outreachDraft:string; summary:string; evidenceConfidence:string; evidenceNote:string; qualityScore:number; qualityBreakdown:Record<string,number>; fitScore:number; fitBreakdown:Record<string,number>; reasons:string[]; qualificationGaps:string[]; qualified:boolean; userState:LeadState; syncedAt:string };
type SourceState = { source:string; status:string; itemCount:number; error:string|null; lastSyncedAt:string };
type FeedbackItem = { id:string; userId:string; message:string; createdAt:string };
type Watchlist = { id:string; name:string; stacks:string[]; categories:string[]; minReward:number; verifiedOnly:boolean; active:boolean };

const defaults: Profile = { displayName:"", goals:[], stacks:[], chains:[], specialties:[], experienceLevel:"Growing", portfolioUrl:"", minReward:0, availability:"Flexible", region:"Global", scopedOnly:true, alertFrequency:"Daily", alertChannel:"In-app", alertDestination:"", passportHeadline:"Independent Web3 security researcher", passportBio:"", passportSlug:"", passportPublic:false, githubUrl:"", auditReportUrls:[], onboardingComplete:false };
const options = {
  goals:["Bug bounties","Audit contests","Direct clients","Security jobs","Grants","Hackathons"],
  stacks:["Solidity / EVM","Rust","Move","Cairo","Soroban","Web / API"],
  chains:["Ethereum","Solana","Stellar","Sui","Aptos","Starknet","Cosmos","Multi-chain"],
  specialties:["DeFi","Bridges","Wallets","Payments","Privacy","Access control","Infrastructure","Stablecoins"],
};
const tabNames=["Qualified","All opportunities","Bug bounties","Audit contests","New protocols","Saved","Pitched","Hidden"];

function Logo() { return <span className="logo"><span className="logo-mark" aria-hidden="true"><i/><i/><i/></span><span>PROSKOPOS</span></span>; }
function initials(value:string) { return value.split(/\s+/).map((word) => word[0]).join("").slice(0,2).toUpperCase() || "P"; }
function relative(value:string|null) { if (!value) return "Not synced yet"; const minutes=Math.round((Date.now()-new Date(value).getTime())/60000); return minutes < 2 ? "just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.floor(minutes/60)}h ago` : `${Math.floor(minutes/1440)}d ago`; }

function GoogleSignIn({clientId,onSuccess,id="google-signin"}:{clientId:string;onSuccess?:(user:{email:string;displayName:string})=>void;id?:string}){useEffect(()=>{if(!clientId)return;const start=()=>{const target=document.getElementById(id);if(!target||!window.google)return;target.replaceChildren();window.google.accounts.id.initialize({client_id:clientId,callback:async({credential})=>{const response=await fetch("/api/auth/google",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({credential})});const data=await response.json();if(response.ok){if(onSuccess)onSuccess(data.user);else window.location.reload()}}});window.google.accounts.id.renderButton(target,{theme:"outline",size:"large",shape:"pill",text:"continue_with"})};const existing=document.querySelector<HTMLScriptElement>('script[src="https://accounts.google.com/gsi/client"]');if(existing){start();return}const script=document.createElement("script");script.src="https://accounts.google.com/gsi/client";script.async=true;script.onload=start;document.head.appendChild(script)},[clientId,id,onSuccess]);return <div id={id} className="google-signin"/>}

function ChoiceGroup({ label, values, selected, onChange }:{ label:string; values:string[]; selected:string[]; onChange:(value:string[])=>void }) {
  return <fieldset className="choice-group"><legend>{label}</legend><div className="choices">{values.map((value) => <button type="button" key={value} className={selected.includes(value) ? "choice active" : "choice"} aria-pressed={selected.includes(value)} onClick={() => onChange(selected.includes(value) ? selected.filter((item) => item !== value) : [...selected,value])}>{value}</button>)}</div></fieldset>;
}

function Onboarding({ initial, name, onSave }:{ initial:Profile|null; name:string; onSave:(profile:Profile)=>Promise<void> }) {
  const [form,setForm]=useState<Profile>({ ...defaults, ...initial, displayName:initial?.displayName || name });
  const [step,setStep]=useState(1); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  async function finish() { if (!form.goals.length || !form.stacks.length) { setError("Choose at least one goal and one stack."); return; } setSaving(true); setError(""); try { await onSave(form); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save profile"); } finally { setSaving(false); } }
  return <div className="onboarding-shell"><div className="onboarding-card">
    <div className="onboarding-top"><Logo/><span>Profile {step} / 3</span></div>
    <div className="progress"><i style={{width:`${step*33.34}%`}}/></div>
    {step===1 && <section><p className="eyebrow">Personalize your radar</p><h1>What should Proskopos qualify for you?</h1><p className="lede">Qualified is calculated from opportunity quality and your actual fit. It is no longer a manual CRM status.</p><ChoiceGroup label="Your goals" values={options.goals} selected={form.goals} onChange={(goals)=>setForm({...form,goals})}/><ChoiceGroup label="Your stacks" values={options.stacks} selected={form.stacks} onChange={(stacks)=>setForm({...form,stacks})}/></section>}
    {step===2 && <section><p className="eyebrow">Technical fit</p><h1>Where are you strongest?</h1><p className="lede">These answers power your Personal Fit score and the “why this qualifies” explanation.</p><ChoiceGroup label="Chains and ecosystems" values={options.chains} selected={form.chains} onChange={(chains)=>setForm({...form,chains})}/><ChoiceGroup label="Security specialties" values={options.specialties} selected={form.specialties} onChange={(specialties)=>setForm({...form,specialties})}/><div className="form-grid"><label>Experience<select value={form.experienceLevel} onChange={(event)=>setForm({...form,experienceLevel:event.target.value})}><option>Growing</option><option>Experienced</option><option>Expert</option></select></label><label>Portfolio URL<input value={form.portfolioUrl} placeholder="https://github.com/you" onChange={(event)=>setForm({...form,portfolioUrl:event.target.value})}/></label></div></section>}
    {step===3 && <section><p className="eyebrow">Practical filters</p><h1>Set your working preferences.</h1><div className="form-grid"><label>Minimum reward / budget (USD)<input type="number" min="0" value={form.minReward} onChange={(event)=>setForm({...form,minReward:Number(event.target.value)})}/></label><label>Availability<select value={form.availability} onChange={(event)=>setForm({...form,availability:event.target.value})}><option>Flexible</option><option>Short scopes only</option><option>1-2 weeks</option><option>2-4 weeks</option><option>Open for retainers</option></select></label><label>Region / eligibility<input value={form.region} onChange={(event)=>setForm({...form,region:event.target.value})}/></label><label>Alert frequency<select value={form.alertFrequency} onChange={(event)=>setForm({...form,alertFrequency:event.target.value})}><option>Instant</option><option>Daily</option><option>Weekly</option><option>Off</option></select></label></div><label className="check"><input type="checkbox" checked={form.scopedOnly} onChange={(event)=>setForm({...form,scopedOnly:event.target.checked})}/><span><b>Permission-first outreach only</b><small>Prioritize scoped programs and public business contacts. Never imply permission to test an unscoped project.</small></span></label><div className="notice">Your Daily Signal can arrive in-app or by email. You can change this any time.</div></section>}
    {error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions">{step>1 && <button className="button ghost" onClick={()=>setStep(step-1)}>Back</button>}<span/>{step<3 ? <button className="button primary" onClick={()=>setStep(step+1)}>Continue</button> : <button className="button primary" disabled={saving} onClick={finish}>{saving ? "Building radar..." : "Build my radar"}</button>}</div>
  </div></div>;
}

function Score({ label, value, accent=false }:{ label:string; value:number; accent?:boolean }) { return <div className={accent ? "score accent" : "score"}><span>{label}</span><b>{value}</b><i><em style={{width:`${value}%`}}/></i></div>; }

function OpportunityCard({ lead, update }:{ lead:Lead; update:(id:string, patch:Partial<LeadState>&{pitched?:boolean})=>Promise<void> }) {
  const [open,setOpen]=useState(false); const [notes,setNotes]=useState(lead.userState.notes); const [nextAction,setNextAction]=useState(lead.userState.nextActionAt?.slice(0,10)||""); const [outcomeNote,setOutcomeNote]=useState(lead.userState.outcomeNote||""); const [busy,setBusy]=useState("");
  const act=async(name:string,patch:Partial<LeadState>&{pitched?:boolean})=>{setBusy(name);try{await update(lead.id,patch);}finally{setBusy("");}};
  const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);setBusy(label);window.setTimeout(()=>setBusy(""),1200)};
  return <article className={`opportunity-card ${lead.qualified ? "is-qualified" : ""}`}>
    <div className="card-top"><div><span className="source">{lead.source}</span><span className={`evidence ${lead.evidenceConfidence}`}>{lead.evidenceConfidence}</span></div>{lead.qualified && <span className="qualified-badge">Qualified</span>}</div>
    <div className="card-title-row"><h3>{lead.project}</h3><span className="stack-chip">{lead.stack}</span></div><p className="summary">{lead.summary}</p>
    <div className="score-pair"><Score label="Opportunity quality" value={lead.qualityScore}/><Score label="Your fit" value={lead.fitScore} accent/></div>
    <div className="card-meta"><div><small>REWARD / SIGNAL</small><strong>{lead.reward}</strong></div><div><small>DEADLINE</small><strong>{lead.deadline}</strong></div></div>
    <div className="card-actions"><button className={lead.userState.saved ? "icon-action active" : "icon-action"} onClick={()=>act("save",{saved:!lead.userState.saved})}>{busy==="save"?"...":lead.userState.saved?"Saved":"Save"}</button><button className={lead.userState.pitchedAt ? "icon-action active" : "icon-action"} onClick={()=>act("pitch",{pitched:!lead.userState.pitchedAt})}>{lead.userState.pitchedAt?"Pitched":"Mark pitched"}</button><a className="apply" href={lead.sourceUrl} target="_blank" rel="noreferrer">Open source</a></div>
    {lead.userState.pitchedAt&&<div className="outcome-prompt"><label>What happened next?<select value={lead.userState.outcome||""} onChange={(event)=>act("outcome",{outcome:event.target.value})}><option value="">No outcome yet</option><option>Got a reply</option><option>Scope discussion</option><option>Paid engagement</option><option>Not a fit</option></select></label><label>Optional learning note<input value={outcomeNote} onChange={(event)=>setOutcomeNote(event.target.value)} onBlur={()=>act("outcome-note",{outcomeNote})} placeholder="What made this work�or not?"/></label></div>}
    <button className="explain-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?"Close workspace":lead.qualified?"Why this qualifies + prepare scope":"What would qualify me?"}<span>{open?"-":"+"}</span></button>
    {open && <div className="evidence-panel">
      <div className={lead.qualified?"fit-explanation fit-ready":"fit-explanation fit-gap"}><h4>{lead.qualified?"Why it matches":"Your shortest path to a match"}</h4><ul>{(lead.qualified?lead.reasons:lead.qualificationGaps).map((reason)=><li key={reason}>{reason}</li>)}</ul></div>
      <h4>Verified evidence</h4><p>{lead.evidenceNote}</p><dl><div><dt>Launch stage</dt><dd>{lead.launchStage}</dd></div><div><dt>Existing audit evidence</dt><dd>{lead.existingAudits}</dd></div><div><dt>Contact route</dt><dd>{lead.contact}</dd></div></dl>
      <div className="scope-workspace"><div className="scope-workspace-head"><div><small>SCOPE WORKSPACE</small><h4>Turn the signal into a responsible first conversation.</h4></div><button onClick={()=>copy(lead.suggestedScope,"scope")}>{busy==="scope"?"Copied":"Copy scope"}</button></div><p className="scope-brief">{lead.suggestedScope}</p><div className="scope-checks"><span>? Confirm official in-scope repositories</span><span>? Review safe-harbor and disclosure rules</span><span>? Check recent contract and dependency changes</span><span>? Agree deliverables, timing, and budget</span></div><label>Suggested outreach<textarea readOnly value={lead.outreachDraft}/></label><button className="button small" onClick={()=>copy(lead.outreachDraft,"outreach")}>{busy==="outreach"?"Outreach copied":"Copy tailored outreach"}</button></div>
      <label>Private notes<textarea value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="Context, contact history, or questions..."/></label><label>Next action date<input type="date" value={nextAction} onChange={(event)=>setNextAction(event.target.value)}/></label><div className="detail-actions"><button className="button small" onClick={()=>act("notes",{notes,nextActionAt:nextAction||null})}>Save private notes</button><button className="text-action danger" onClick={()=>act("hide",{hidden:true})}>Hide opportunity</button></div>
    </div>}
  </article>;
}

function Settings({ profile, userEmail, close, save, emailPreview }:{ profile:Profile; userEmail:string; close:()=>void; save:(profile:Profile)=>Promise<void>; emailPreview:()=>Promise<void> }) {
  const [form,setForm]=useState(profile); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [reports,setReports]=useState(profile.auditReportUrls.join("\n"));
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Radar settings"><div className="settings-panel"><div className="panel-head"><div><p className="eyebrow">Private profile</p><h2>Radar settings</h2></div><button className="close" onClick={close} aria-label="Close settings">�</button></div><ChoiceGroup label="Goals" values={options.goals} selected={form.goals} onChange={(goals)=>setForm({...form,goals})}/><ChoiceGroup label="Stacks" values={options.stacks} selected={form.stacks} onChange={(stacks)=>setForm({...form,stacks})}/><ChoiceGroup label="Chains" values={options.chains} selected={form.chains} onChange={(chains)=>setForm({...form,chains})}/><ChoiceGroup label="Specialties" values={options.specialties} selected={form.specialties} onChange={(specialties)=>setForm({...form,specialties})}/><div className="form-grid"><label>Experience<select value={form.experienceLevel} onChange={(e)=>setForm({...form,experienceLevel:e.target.value})}><option>Growing</option><option>Experienced</option><option>Expert</option></select></label><label>Minimum reward<input type="number" value={form.minReward} onChange={(e)=>setForm({...form,minReward:Number(e.target.value)})}/></label><label>Alert frequency<select value={form.alertFrequency} onChange={(e)=>setForm({...form,alertFrequency:e.target.value})}><option>Instant</option><option>Daily</option><option>Weekly</option><option>Off</option></select></label><label>Alert channel<select value={form.alertChannel} onChange={(e)=>setForm({...form,alertChannel:e.target.value})}><option>In-app</option><option>Email</option></select></label><label className="wide">Notification email<input type="email" value={form.alertDestination} placeholder={userEmail} onChange={(e)=>setForm({...form,alertDestination:e.target.value})}/></label></div>
    <section className="passport-settings"><p className="eyebrow">Security Passport</p><h3>Shape your public proof of work.</h3><div className="form-grid"><label className="wide">Professional headline<input value={form.passportHeadline} onChange={(e)=>setForm({...form,passportHeadline:e.target.value})}/></label><label className="wide">Short bio<textarea value={form.passportBio} onChange={(e)=>setForm({...form,passportBio:e.target.value})} placeholder="Your approach, strongest experience, and the scopes you want."/></label><label>Public link slug<input value={form.passportSlug} onChange={(e)=>setForm({...form,passportSlug:e.target.value})} placeholder="your-name"/></label><label>GitHub URL<input value={form.githubUrl} onChange={(e)=>setForm({...form,githubUrl:e.target.value})}/></label><label className="wide">Public audit reports, one URL per line<textarea value={reports} onChange={(e)=>setReports(e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={form.passportPublic} onChange={(e)=>setForm({...form,passportPublic:e.target.checked})}/><span><b>Make my Security Passport public</b><small>Your email, saved leads, notes, and preferences are never shown.</small></span></label></section>
    <div className="auth-readiness"><span>G</span><div><b>Google sign-in active</b><small>Your Google account protects your private profile, saved opportunities, notes, and outreach history.</small></div></div>{message&&<p className="success">{message}</p>}<div className="panel-actions wrap"><button className="button ghost" onClick={close}>Cancel</button><button className="button ghost" type="button" onClick={async()=>{setMessage("Sending a private preview...");try{await emailPreview();setMessage("Daily Signal preview sent.");}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not send preview.");}}}>Send email preview</button><button className="button primary" disabled={saving} onClick={async()=>{setSaving(true);await save({...form,auditReportUrls:reports.split(/\r?\n/).map((item)=>item.trim()).filter(Boolean)});setMessage("Settings saved and scores recalculated.");setSaving(false);}}>{saving?"Saving...":"Save settings"}</button></div></div></div>;
}

function SecurityPassport({profile,qualified,verified,close,edit}:{profile:Profile;qualified:number;verified:number;close:()=>void;edit:()=>void}){
  const code=(profile.passportSlug||profile.displayName).split("").reduce((sum,character)=>sum+character.charCodeAt(0),0).toString(16).toUpperCase().padStart(6,"0").slice(-6);
  const share=profile.passportPublic&&profile.passportSlug?`${window.location.origin}/passport/${profile.passportSlug}`:"";
  return <div className="modal-backdrop passport-modal" role="dialog" aria-modal="true" aria-label="Security Passport"><div className="passport-preview-panel"><button className="close" onClick={close}>�</button><div className="passport-preview-copy"><p className="eyebrow">Your professional signal</p><h2>A Security Passport that feels earned�not templated.</h2><p>Share a clean, permission-first proof of focus without exposing your private opportunity pipeline.</p></div><article className="security-passport-card compact"><div className="passport-orbit" aria-hidden="true"><i/><i/><i/></div><header><div><small>SECURITY PASSPORT</small><b>P-{code}</b></div><span className="passport-live"><i/> {profile.availability.toUpperCase()}</span></header><div className="passport-identity"><div className="passport-portrait">{initials(profile.displayName)}</div><div><p>RESEARCHER</p><h2>{profile.displayName}</h2><strong>{profile.passportHeadline}</strong></div></div><div className="passport-field-grid"><div><small>CORE STACKS</small><p>{profile.stacks.slice(0,3).join(" � ")}</p></div><div><small>LIVE MATCHES</small><p>{qualified} qualified � {verified} verified</p></div></div><footer><span>Owner verified � Permission-first</span><b>PROSKOPOS / {code}</b></footer></article><div className="passport-share">{share?<><input readOnly value={share}/><button onClick={async()=>navigator.clipboard.writeText(share)}>Copy public link</button></>:<p>Your Passport is private. Publish it when the details feel ready.</p>}<button className="button ghost" onClick={edit}>Edit Passport</button></div></div></div>
}

function DailySignal({leads,watchlists,profile,close,createWatch,removeWatch,sendEmail}:{leads:Lead[];watchlists:Watchlist[];profile:Profile;close:()=>void;createWatch:(value:Partial<Watchlist>)=>Promise<void>;removeWatch:(id:string)=>Promise<void>;sendEmail:()=>Promise<void>}){
  const [name,setName]=useState("");const [stack,setStack]=useState(profile.stacks[0]||"");const [minReward,setMinReward]=useState(profile.minReward);const [verifiedOnly,setVerifiedOnly]=useState(true);const [message,setMessage]=useState("");
  const top=[...leads].filter((lead)=>!lead.userState.hidden).sort((a,b)=>Number(b.qualified)-Number(a.qualified)||(b.fitScore+b.qualityScore)-(a.fitScore+a.qualityScore)).slice(0,3);
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Daily Signal"><div className="signal-panel"><button className="close" onClick={close}>�</button><p className="eyebrow">Daily Signal</p><h2>Your best opportunities, before the window moves.</h2><p className="signal-intro">A concise personal briefing�not another noisy feed.</p><div className="signal-top">{top.map((lead,index)=><article key={lead.id}><span>0{index+1}</span><div><small>{lead.qualified?"QUALIFIED":"NEAREST FIT"} � {lead.source}</small><h3>{lead.project}</h3><p>{lead.fitScore}/100 fit � {lead.reward} � {lead.deadline}</p></div></article>)}</div><section className="watch-builder"><div><h3>Saved watches</h3><p>Tell Proskopos what deserves an alert.</p></div><div className="watch-form"><input value={name} onChange={(event)=>setName(event.target.value)} placeholder="e.g. Soroban audits above $5k"/><select value={stack} onChange={(event)=>setStack(event.target.value)}><option value="">Any stack</option>{options.stacks.map((item)=><option key={item}>{item}</option>)}</select><input type="number" min="0" value={minReward} onChange={(event)=>setMinReward(Number(event.target.value))}/><label className="mini-check"><input type="checkbox" checked={verifiedOnly} onChange={(event)=>setVerifiedOnly(event.target.checked)}/> Verified evidence only</label><button onClick={async()=>{await createWatch({name:name||`${stack||"All"} opportunities`,stacks:stack?[stack]:[],categories:[],minReward,verifiedOnly,active:true});setName("");}}>Add watch</button></div><div className="watch-list">{watchlists.length?watchlists.map((watch)=><div key={watch.id}><i/><span><b>{watch.name}</b><small>{watch.stacks.join(", ")||"Any stack"} � {watch.minReward?`$${watch.minReward.toLocaleString()}+`:"Any budget"}{watch.verifiedOnly?" � verified":""}</small></span><button onClick={()=>removeWatch(watch.id)}>Remove</button></div>):<p>No saved watches yet. Your general profile still powers the briefing.</p>}</div></section><div className="signal-email"><div><b>{profile.alertFrequency} email briefing</b><span>{profile.alertChannel==="Email"?"Email delivery is selected.":"Choose Email in radar settings to automate delivery."}</span></div><button onClick={async()=>{setMessage("Sending...");try{await sendEmail();setMessage("Preview sent to your notification email.");}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not send preview.");}}}>Send preview</button></div>{message&&<p className="success">{message}</p>}</div></div>
}

export function ProskoposApp() {
  const [user,setUser]=useState<{displayName:string;email:string}|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [leads,setLeads]=useState<Lead[]>([]); const [sources,setSources]=useState<SourceState[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [tab,setTab]=useState("Qualified"); const [search,setSearch]=useState(""); const [source,setSource]=useState("All sources"); const [settings,setSettings]=useState(false); const [syncing,setSyncing]=useState(false); const [lastSynced,setLastSynced]=useState<string|null>(null); const [feedbackOpen,setFeedbackOpen]=useState(false); const [feedbackInboxOpen,setFeedbackInboxOpen]=useState(false); const [feedbackItems,setFeedbackItems]=useState<FeedbackItem[]>([]); const [feedback,setFeedback]=useState(""); const [toast,setToast]=useState(""); const [googleId,setGoogleId]=useState(""); const [isOwner,setIsOwner]=useState(false);
  const [workspaceOpen,setWorkspaceOpen]=useState(false); const [signalOpen,setSignalOpen]=useState(false); const [passportOpen,setPassportOpen]=useState(false); const [watchlists,setWatchlists]=useState<Watchlist[]>([]);
  async function load() { setLoading(true); setError(""); try { const meResponse=await fetch("/api/me"); const me=await meResponse.json(); setUser(me.user); setProfile(me.profile); setGoogleId(me.googleClientId||""); setIsOwner(!!me.isOwner); if(!me.user){setLeads([]);setSources([]);setLastSynced(null);return;} const [leadsResponse,watchResponse]=await Promise.all([fetch("/api/leads"),fetch("/api/watchlists")]); const data=await leadsResponse.json(); const watchData=await watchResponse.json(); if(!leadsResponse.ok) throw new Error(data.error||"Could not load radar"); setLeads(data.leads||[]); setSources(data.sources||[]); setLastSynced(data.lastSynced); setWatchlists(watchResponse.ok?watchData.watchlists||[]:[]); } catch(cause){setError(cause instanceof Error?cause.message:"Could not load radar");} finally{setLoading(false);} }
  // The initial request is intentionally client-side so the private session header reaches the API.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  useEffect(()=>{if(!profile?.onboardingComplete)return;const nodes=Array.from(document.querySelectorAll<HTMLElement>(".woodland-app > section, .qualification-outcome, .trail-grid article, .involved-grid article"));const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}}),{threshold:.14,rootMargin:"0px 0px -6% 0px"});nodes.forEach((node)=>{node.classList.add("reveal-on-scroll");observer.observe(node);});return()=>observer.disconnect();},[profile?.onboardingComplete,workspaceOpen]);
  async function saveProfile(value:Profile) { const response=await fetch("/api/me",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)}); const data=await response.json(); if(!response.ok) throw new Error(data.error||"Could not save profile"); setProfile(data.profile); setSettings(false); await load(); }
  async function sendEmailPreview(){const response=await fetch("/api/notifications/email",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not send email.");setToast(`Daily Signal sent to ${data.destination}.`);}
  async function createWatch(value:Partial<Watchlist>){const response=await fetch("/api/watchlists",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save watch.");setWatchlists((current)=>[data.watchlist,...current.filter((item)=>item.id!==data.watchlist.id)]);}
  async function removeWatch(id:string){const response=await fetch(`/api/watchlists?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!response.ok)throw new Error("Could not remove watch.");setWatchlists((current)=>current.filter((item)=>item.id!==id));}
  async function updateLead(id:string,patch:Partial<LeadState>&{pitched?:boolean}) { setLeads((current)=>current.map((lead)=>lead.id===id?{...lead,userState:{...lead.userState,...patch,pitchedAt:typeof patch.pitched==="boolean"?(patch.pitched?new Date().toISOString():null):lead.userState.pitchedAt}}:lead)); const response=await fetch(`/api/leads/${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}); const data=await response.json(); if(!response.ok){await load();throw new Error(data.error||"Could not update opportunity");} setLeads((current)=>current.map((lead)=>lead.id===id?{...lead,userState:data.userState}:lead)); }
  async function sync() { setSyncing(true);setError("");try{const response=await fetch("/api/leads",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Sync failed");setToast(`${data.added} verified and inferred records refreshed.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Sync failed");}finally{setSyncing(false);} }
  async function openFeedbackInbox() { const response=await fetch("/api/feedback"); const data=await response.json(); if(!response.ok){setError(data.error||"Could not load feedback");return;} setFeedbackItems(data.items||[]); setFeedbackInboxOpen(true); }
  async function signOut() { await fetch("/api/auth/logout",{method:"POST"}); window.location.reload(); }
  const counts=useMemo(()=>Object.fromEntries(tabNames.map((item)=>[item,leads.filter((lead)=>item==="Qualified"?lead.qualified&&!lead.userState.hidden:item==="All opportunities"?!lead.userState.hidden:item==="Bug bounties"?lead.category==="Bug bounty"&&!lead.userState.hidden:item==="Audit contests"?lead.category==="Audit contest"&&!lead.userState.hidden:item==="New protocols"?lead.category==="New protocol"&&!lead.userState.hidden:item==="Saved"?lead.userState.saved&&!lead.userState.hidden:item==="Pitched"?!!lead.userState.pitchedAt&&!lead.userState.hidden:lead.userState.hidden).length])),[leads]);
  const visible=useMemo(()=>leads.filter((lead)=>{const tabMatch=tab==="Qualified"?lead.qualified&&!lead.userState.hidden:tab==="All opportunities"?!lead.userState.hidden:tab==="Bug bounties"?lead.category==="Bug bounty"&&!lead.userState.hidden:tab==="Audit contests"?lead.category==="Audit contest"&&!lead.userState.hidden:tab==="New protocols"?lead.category==="New protocol"&&!lead.userState.hidden:tab==="Saved"?lead.userState.saved&&!lead.userState.hidden:tab==="Pitched"?!!lead.userState.pitchedAt&&!lead.userState.hidden:lead.userState.hidden;const query=`${lead.project} ${lead.source} ${lead.stack} ${lead.summary}`.toLowerCase();return tabMatch&&(source==="All sources"||lead.source===source)&&query.includes(search.toLowerCase());}),[leads,tab,source,search]);
  const qualifiedLead=leads.find((lead)=>lead.qualified&&!lead.userState.hidden);
  const bestLead=useMemo(()=>[...leads].filter((lead)=>!lead.userState.hidden).sort((a,b)=>(b.fitScore+b.qualityScore)-(a.fitScore+a.qualityScore))[0],[leads]);
  const spotlight=visible[0]||qualifiedLead||bestLead;
  const shown=visible.slice(0,9);
  if(loading) return <main className="loading-screen"><Logo/><div className="radar-loader"><i/><i/><i/></div><p>Collecting evidence and calculating your fit...</p></main>;
  if(!user) return <div className="public-entry"><header className="app-header reference-nav public-nav"><div className="header-links"><span>Opportunity intelligence</span></div><Logo/><div className="header-right google-entry">{googleId?<GoogleSignIn id="google-header-signin" clientId={googleId}/>:<div className="notice">Google sign-in is temporarily unavailable.</div>}</div></header><main><section className="radar-hero generated-hero public-hero"><h1 className="sr-only">Find Web3 security work that fits.</h1><img src="/og.png" alt="Proskopos opportunity forest with Web3 security signals"/><div className="hero-afterword"><p>Every promising scope leaves a signal. Sign in with Google to turn those signals into a private radar shaped around your expertise, availability, and ambitions.</p><span className="signin-caption">Your profile, saved leads, and notes stay private.</span></div></section></main></div>;
  if(!profile?.onboardingComplete) return <Onboarding initial={profile} name={user.displayName} onSave={saveProfile}/>;
  return <div className="app-shell">
    <header className="app-header reference-nav"><nav className="header-links" aria-label="Page navigation"><button onClick={()=>document.querySelector(".lore-scene")?.scrollIntoView({behavior:"smooth"})}>The signal</button><button onClick={()=>document.querySelector(".trail-section")?.scrollIntoView({behavior:"smooth"})}>Audit trail</button><button onClick={()=>{setWorkspaceOpen(true);window.setTimeout(()=>document.getElementById("radar")?.scrollIntoView({behavior:"smooth"}),40)}}>My radar</button></nav><Logo/><div className="header-right"><button className="header-tool" onClick={()=>setSignalOpen(true)}>Daily signal</button><button className="header-tool passport-tool" onClick={()=>setPassportOpen(true)}>Security Passport</button>{isOwner&&<button className="owner-inbox-button" onClick={openFeedbackInbox}>Feedback inbox</button>}<button className="sync-status" onClick={sync} disabled={syncing}><i className={syncing?"spinning":""}/>{syncing?"Syncing...":relative(lastSynced)}</button><button className="avatar" onClick={()=>setSettings(true)} aria-label="Open profile settings">{initials(profile.displayName)}</button><button className="sign-out-link" onClick={signOut}>Sign out</button></div></header>
    <main>
      <section className="radar-hero generated-hero"><h1 className="sr-only">Find Web3 security work that fits.</h1><img src="/og.png" alt="Proskopos opportunity forest with Web3 security signals"/><div className="hero-afterword"><p>Every promising scope leaves a signal. Proskopos brings the right ones into focus—verified by evidence, aligned with your expertise, and ready when you are.</p><button onClick={()=>document.querySelector(".lore-scene")?.scrollIntoView({behavior:"smooth"})}>Follow the signal</button></div><div className="hero-stats"><span><b>{counts.Qualified}</b> matches for you</span><span><b>{leads.filter((lead)=>lead.evidenceConfidence==="verified").length}</b> verified opportunities</span><span><b>{sources.filter((item)=>item.status==="ok").length}/{sources.length}</b> sources reporting</span></div></section>
      <section className={`qualification-outcome ${counts.Qualified?"has-match":"no-match"}`}><div><p className="story-kicker">Your qualification result</p><h2>{counts.Qualified?`You qualify for ${counts.Qualified} ${counts.Qualified===1?"opportunity":"opportunities"} right now.`:"No exact match yet. Your closest lead is still worth seeing."}</h2><p>{counts.Qualified&&qualifiedLead?`${qualifiedLead.project} leads your radar with a ${qualifiedLead.fitScore}/100 personal fit score.`:bestLead?`${bestLead.project} is currently your nearest visible fit at ${bestLead.fitScore}/100. ${bestLead.qualificationGaps?.[0]||"Refine your profile or review the evidence before deciding whether to approach."}`:"The radar is collecting fresh opportunities. Your profile is ready for the next matching signal."}</p></div><button onClick={()=>{setTab(counts.Qualified?"Qualified":"All opportunities");setWorkspaceOpen(true);window.setTimeout(()=>document.getElementById("radar")?.scrollIntoView({behavior:"smooth"}),40)}}>{counts.Qualified?"See my qualified matches":"See my closest leads"}</button></section>
      <div className="woodland-app">
        {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}{toast&&<div className="toast">{toast}<button onClick={()=>setToast("")}>×</button></div>}
        <section className="lore-scene">
          <div className="forest-layer forest-back" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="forest-layer forest-front" aria-hidden="true"><i/><i/><i/><i/></div>
          <div className="radar-tree tree-one" aria-hidden="true"><b/><i/><span/></div><div className="radar-tree tree-two" aria-hidden="true"><b/><i/><span/></div>
          <article className="lore-card"><p className="story-kicker">The opportunity forest never stands still</p><h2>Find the signal. Follow the evidence. Reach the right project at the right time.</h2><p>Bounties open, contests move, and new protocols edge toward launch across scattered platforms. Proskopos gathers those moments into one clear trail.</p><p>See why each lead matters, how well it fits, and where permission begins. Less noise. Better timing. Stronger conversations.</p><div className="lore-actions"><button onClick={()=>{setWorkspaceOpen(true);window.setTimeout(()=>document.getElementById("radar")?.scrollIntoView({behavior:"smooth"}),40)}}>Enter the radar</button><button className="quiet" onClick={()=>setSettings(true)}>Tune my profile</button></div></article>
        </section>

        {workspaceOpen&&<section className="directory reference-directory workspace-reveal woodland-radar" id="radar"><div className="workspace-head"><div><p className="eyebrow">Private opportunity workspace</p><h2>Your qualified radar</h2></div><button onClick={()=>setWorkspaceOpen(false)}>Close radar</button></div><div className="tabs" role="tablist" aria-label="Opportunity categories">{tabNames.map((item)=><button role="tab" aria-selected={tab===item} className={tab===item?"active":""} key={item} onClick={()=>setTab(item)}>{item} <span>{counts[item]}</span></button>)}</div><div className="directory-head"><div><p className="section-label">Evidence-backed results</p><h2>{visible.length} opportunities in this view</h2></div><div className="filters"><label className="search"><span>Search</span><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Projects, stacks, sources..."/></label><select value={source} onChange={(event)=>setSource(event.target.value)}><option>All sources</option>{Array.from(new Set(leads.map((lead)=>lead.source))).sort().map((item)=><option key={item}>{item}</option>)}</select></div></div>{visible.length?<><div className="opportunity-grid">{shown.map((lead)=><OpportunityCard key={lead.id} lead={lead} update={updateLead}/>)}</div>{visible.length>9&&<p className="all-results-note">Showing the top 9 by quality and fit. Refine the filters to reach the rest.</p>}</>:<div className="empty-state"><span>0</span><h3>No opportunities in this view yet.</h3><p>Adjust your profile or filters. Qualification requires Opportunity Quality 70+ and Personal Fit 75+.</p><button className="button primary" onClick={()=>setSettings(true)}>Edit profile</button></div>}</section>}

        <section className="involved-section"><p className="section-script">From Signal to Scope</p><div className="involved-grid">
          <article><div className="passport-art" aria-hidden="true"><i/><b>PASS</b><span>01</span></div><h3>Carry proof, not promises</h3><p>Your Security Passport turns stacks, public work, and availability into one distinctive professional signal.</p><button onClick={()=>setPassportOpen(true)}>Open my Passport</button></article>
          <span className="path-arrow" aria-hidden="true">→</span>
          <article><div className="signal-art" aria-hidden="true"><i/><i/><i/><b>86</b></div><h3>Wake up to the right signal</h3><p>Saved watches and your Daily Signal keep high-fit work moving toward you without flooding your inbox.</p><button onClick={()=>setSignalOpen(true)}>Open Daily Signal</button></article>
        </div></section>

        <section className="trail-section"><p className="section-script">A Clearer Trail to Better Work</p><div className="trail-grid">
          <article><div className="trail-art trail-collect"><i/><i/><i/><span>01</span></div><small>Always running</small><h3>Phase 1: See what is emerging</h3><p>Fresh bounties, live contests, and early protocol movement come together in one living opportunity map.</p></article>
          <article><div className="trail-art trail-qualify"><i/><i/><b>Q</b><b>F</b></div><small>Explainable scoring</small><h3>Phase 2: Know why it fits</h3><p>Quality, timing, evidence, stack, and availability become a score you can understand—not a ranking you have to trust blindly.</p></article>
          <article><div className="trail-art trail-outreach"><i/><i/><i/><span>03</span></div><small>Permission first</small><h3>Phase 3: Start the right conversation</h3><p>Review the scope, preserve the context, and approach the project with a responsible audit proposal built for that moment.</p></article>
        </div><button className="trail-button" onClick={()=>{setWorkspaceOpen(true);window.setTimeout(()=>document.getElementById("radar")?.scrollIntoView({behavior:"smooth"}),40)}}>View the full opportunity trail</button></section>

        {spotlight&&<section className="pledge-split"><div className="scope-collage" aria-hidden="true"><div>SMART<br/>CONTRACTS</div><div>VERIFIED<br/>SCOPE</div><div>FIT<br/>{spotlight.fitScore}</div><span>{spotlight.stack}</span></div><div className="pledge-copy"><p className="story-kicker">Strongest signal right now</p><h2>{spotlight.project}</h2><p>{spotlight.summary}</p><p>{spotlight.fitReason}</p><a href={spotlight.sourceUrl} target="_blank" rel="noreferrer">Review official source</a><small>{spotlight.source} · {spotlight.evidenceConfidence} evidence · quality {spotlight.qualityScore}</small></div></section>}

        <section className="feedback-story"><div><p className="story-kicker">Make the radar sharper</p><h2>Every useful signal makes the next search stronger.</h2><p>If a score feels unclear, a source is missing, or a feature could improve your outreach, tell us. Your feedback goes straight to the builder.</p></div><button onClick={()=>setFeedbackOpen(true)}>Send feedback</button></section>
      </div>
    </main>
    <footer className="woodland-footer"><div className="footer-logo"><Logo/><p>Opportunity intelligence for responsible Web3 security work.</p></div><div><b>Get involved</b><button onClick={()=>{setWorkspaceOpen(true);window.setTimeout(()=>document.getElementById("radar")?.scrollIntoView({behavior:"smooth"}),40)}}>Open the radar</button><button onClick={()=>setFeedbackOpen(true)}>Send feedback</button></div><div><b>The product</b><button onClick={()=>setSettings(true)}>Profile settings</button><span>Qualified opportunities</span><span>Private outreach notes</span></div><div><b>Trust</b><a href="/acceptable-use">Permission first</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><div><b>Account</b><span>Google protected</span><span>Public beta</span></div></footer>
    <button className="feedback-fab" onClick={()=>setFeedbackOpen(true)}>Feedback</button>{settings&&<Settings profile={profile} userEmail={user.email} close={()=>setSettings(false)} save={saveProfile} emailPreview={sendEmailPreview}/>} {signalOpen&&<DailySignal leads={leads} watchlists={watchlists} profile={profile} close={()=>setSignalOpen(false)} createWatch={createWatch} removeWatch={removeWatch} sendEmail={sendEmailPreview}/>} {passportOpen&&<SecurityPassport profile={profile} qualified={counts.Qualified} verified={leads.filter((lead)=>lead.evidenceConfidence==="verified").length} close={()=>setPassportOpen(false)} edit={()=>{setPassportOpen(false);setSettings(true)}}/>} {feedbackInboxOpen&&<div className="modal-backdrop"><div className="feedback-inbox"><button className="close" onClick={()=>setFeedbackInboxOpen(false)} aria-label="Close feedback inbox">×</button><p className="eyebrow">Owner inbox</p><h2>User feedback</h2><p className="inbox-intro">The latest 100 messages sent through the feedback button.</p><div className="feedback-list">{feedbackItems.length?feedbackItems.map((item)=><article key={item.id}><div><b>{item.userId}</b><time>{new Date(item.createdAt).toLocaleString()}</time></div><p>{item.message}</p></article>):<p>No feedback has arrived yet.</p>}</div></div></div>} {feedbackOpen&&<div className="modal-backdrop"><form className="feedback-panel" onSubmit={async(event:FormEvent)=>{event.preventDefault();const response=await fetch("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:feedback})});if(response.ok){setFeedbackOpen(false);setFeedback("");setToast("Thanks - your feedback was saved privately.");}}}><button type="button" className="close" onClick={()=>setFeedbackOpen(false)}>x</button><p className="eyebrow">Public beta feedback</p><h2>What should we improve?</h2><textarea required minLength={3} value={feedback} onChange={(event)=>setFeedback(event.target.value)} placeholder="Tell us what felt unclear, missing, or especially useful."/><button className="button primary">Send feedback</button></form></div>}
  </div>;
}
